config/routes.rb
Rails.application.routes.draw do
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  resources :games do 
    resources :messages
  end
  resources :users
  

  root 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, presence: true,
            on: :create,
            confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find(session[:user_id]) if 
    session[:user_id]
  end

  helper_method :current_user
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
     @game = Game.find(params[:id])
     @messages = @game.messages
  end

end

app/controllers/home_controller.rb
class HomeController <ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_game

  def index
    @messages = Message.all
  end

  def create
    @user = current_user.email
    @message = @game.messages.create!(message_params)
    # @message = Message.create!(message_params)
    PrivatePub.publish_to("/messages/#{@game.id}", message: @message )

    respond_to do |format|
      format.js  { render file: "games/create.js.erb"}
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def get_game
    @game = Game.find_by_id(params[:game_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:sign_in][:email])
    if user && user.authenticate(params[:sign_in][:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully signed in!"
      redirect_to root_path
    else
      flash[:alert] = "Invalid email & password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to POST UP!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/create.js.erb
 <% publish_to "/messages/#{@game.id}" do %>
   $("#chat").append("<%= j render(@message) %>");
 <% end %>

$("#new_message")[0].reset();

app/views/games/index.html.erb
<h1>Upcoming NBA lineup</h1>
<div class="container">
  <h3>What's on tap for the NBA today:</h3>

  <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Home Team</th>
        <th>Away Team</th>
        <th>Game Time (date/time)</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
      <tr>
        <td><%= link_to 'Discuss', game_path(game), class: 'btn btn-success' %></td>
        <td><%= game.home_team %></td>
        <td><%= game.away_team %></td>
        <td><%= game.game_time %></td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/games/show.html.erb
<h2 class="text-center"><%= @game.home_team %> v. <%= @game.away_team %></h2>

<h5 class="text-center"> Post up! There's a lot to talk about. </h5>

<ul id="chat">
  <%= render @messages %>
</ul>

<%= form_for [@game, Message.new], url: game_messages_path(@game), remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/#{@game.id}" %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>POST UP</h1>
  <p>All your sports chatter, all in one place. </p> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Post Up', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
         <li><%= link_to "Create account", new_user_path %>
        </li>
        <li><%= link_to "Upcoming Games", games_path %>
        </li>
        <% if current_user %>
          <li <p class="navbar-text">Signed in as <%= current_user.email %></p>
          </li>
          <li><%= link_to "Sign Out", sign_out_path, method: :delete %>
          </li>
        <% else %>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostUp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <section>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </section>

</body>
</html>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  <span class="user_email">
    <%= "#{current_user.email}" %>
  </span>
  <%= message.content %>

</li>

app/views/messages/create.js.erb
 <% publish_to "game_chat_#{@game.id}" do %>
   $("#chat_game_#{@game.id}").append("<%= j render(@message) %>");
 <% end %>

$("#new_message")[0].reset();

app/views/messages/index.html.erb
<h1> Chat </h1>

<ul id="chat">
  <%= render @messages %>
</ul>

<%= form_for Message.new, remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "Send" %>
<% end %>

<%= subscribe_to "/messages/new" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="row">
  <div class="col-md-4">
    <%= simple_form_for User.new do |f| %>
      <%=f.input :full_name, label: 'Your name:' %>
      <%=f.input :email, label: 'Your email:', placeholder: 'user@domain.com' %>
      <%=f.input :password, label: 'Create a password:' %>
      <%=f.input :password_confirmation, label: 'Type your password again:' %>
      <%=f.button :submit, label: "Sign Up" %>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<h1>Your profile</h1>